apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: mptransaction-sink
  annotations:
    camel.apache.org/kamelet.icon: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pg0KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE2LjAuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPg0KPCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCINCgkgd2lkdGg9IjUxMnB4IiBoZWlnaHQ9IjUxMnB4IiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgNTEyIDUxMjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPGc+DQoJPHBhdGggZD0iTTQ0OCwwSDY0QzQ2LjMyOCwwLDMyLDE0LjMxMywzMiwzMnY0NDhjMCwxNy42ODgsMTQuMzI4LDMyLDMyLDMyaDM4NGMxNy42ODgsMCwzMi0xNC4zMTIsMzItMzJWMzINCgkJQzQ4MCwxNC4zMTMsNDY1LjY4OCwwLDQ0OCwweiBNNjQsNDgwVjEyOGg4MHY2NEg5NnYxNmg0OHY0OEg5NnYxNmg0OHY0OEg5NnYxNmg0OHY0OEg5NnYxNmg0OHY4MEg2NHogTTQ0OCw0ODBIMTYwdi04MGgyNTZ2LTE2DQoJCUgxNjB2LTQ4aDI1NnYtMTZIMTYwdi00OGgyNTZ2LTE2SDE2MHYtNDhoMjU2di0xNkgxNjB2LTY0aDI4OFY0ODB6Ii8+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8L3N2Zz4NCg=="
    camel.apache.org/provider: "Red Hat GPS"
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "Mp Tansaction Rest Sink"
    description: |-
      Comunicación con el servicio web REST MP Transaction.
    required:
    - url
    - headerId
    - headerToken  
    type: object
    properties:
      loggerName:
        title: Logger Name
        description: Name of the logging category to use
        type: string
        default: "log-sink"
      url:
        title: URL Monitor
        description: URL de conexión al servicio monitor
        type: string
      method:  
        title: Method
        description: The HTTP method to use.
        type: string
        default: POST
        enum: ["GET", "POST", "PUT", "DELETE", "HEAD", "OPTIONS", "TRACE", "PATCH"]
      headerId:
        title: Header ID
        description: Valor del Header ID a enviar.
        type: string
        default: ID
      headerToken:
        title: Header Token
        description: Valor del Header Token a enviar.
        type: string
      contentType:
        title: Content-Type
        description: Content-Type a enviar al servicio.
        type: string
        default: application/json
  dependencies:
  - "camel:kamelet"
  - "camel:log"
  - "camel:http"
  template:
    route:
      stream-cache: true
      message-history: true
      from:
        uri: "kamelet:source"
        steps:
        - log:
            loggingLevel: "INFO"
            message: "Iniciando Llamado a Monitor ${headers} ${body}"
        - log:
            loggingLevel: "INFO"
            message: "Parametros Kamelet {{url}} {{method}} {{headerId}} {{headerToken}} {{contentType}}"
        - setHeader:
            name: CamelHttpMethod
            constant: "{{method}}"
        - setHeader:
            name: ID
            constant: "{{headerId}}"
        - setHeader:
            name: SIGN
            constant: "{{headerToken}}"
        - setHeader:
            name: Content-Type
            constant: "{{contentType}}"
        - log:
            loggingLevel: "INFO"
            message: "Enviando Headers ${headers} al endpoint {{url}}"
        - to: 
            uri: "{{url}}"
            parameters:
              throwExceptionOnFailure: false
        - to:
            uri: "log:{{loggerName}}"
            parameters:
              level: INFO
              showAllProperties: true
              showBody: true
              showHeaders: true
              showProperties: true
        
              
